files test

diff --git a/.github/workflows/files.yml b/.github/workflows/files.yml
--- a/.github/workflows/files.yml
+++ b/.github/workflows/files.yml
@@ -5,15 +5,23 @@ name: Check files
 # Verifies:
 # - the signatures are up-to-date
 # - the release_notes and NEWS are consitent
-# - the C/C++ files have a license
+# - the files have a license
 # - the shell scripts are ok
-# - the code style is ok
 # Does not makes a compilation
 
 on: [push, pull_request]
 
 permissions:
   contents: read
+
+defaults:
+  run:
+    shell: bash
+    working-directory: ./.github/scripts
+
+concurrency:
+  group: ${{ github.workflow }}-${{ github.ref }}
+  cancel-in-progress: true
 
 jobs:
   Signature_check:
@@ -22,8 +30,7 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v4
       - name: Signatures are not removed
-        run: |
-          tools/scripts/test_signatures.sh
+        run: ./test_signatures.sh
 
   News_check:
     runs-on: ubuntu-latest
@@ -31,10 +38,11 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v4
       - name: News file up to date
+        working-directory: ./
         run: |
-          tools/scripts/notes2news.pl
+          .github/scripts/notes2news.pl
           if git status | grep 'NEWS.md'; then echo "NEWS.md is not up to date"; exit 1; fi
-          if ! grep -q $(grep -Po '(?<=project\(PGORTOOLS VERSION )[^;]+' CMakeLists.txt) NEWS.md; then echo "Missing section in NEWS.md"; exit 1; fi
+          if ! grep -q $(grep -Po '(?<=project\(pgORpy VERSION )[^;]+' CMakeLists.txt) NEWS.md; then echo "Missing section in NEWS.md"; exit 1; fi
 
   License_check:
     runs-on: ubuntu-latest
@@ -42,10 +50,9 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v4
       - name: Install Requirements
-        run: |
-          sudo apt install -y licensecheck
+        run:  sudo apt-get install -y licensecheck
       - name: Run License Check
-        run: ./tools/scripts/test_license.sh
+        run: ./test_license.sh
 
   Shell_check:
     runs-on: ubuntu-latest
@@ -53,22 +60,6 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v4
       - name: Install Requirements
-        run: |
-          sudo apt install -y shellcheck
+        run:  sudo apt-get install -y shellcheck
       - name: Run Shell Check
-        run: ./tools/scripts/test_shell.sh
-
-  style-check:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v4
-      - name: Install Requirements
-        uses: actions/checkout@v4
-        with:
-          repository: 'cpplint/cpplint'
-          ref: "develop"
-          path: "code_linter/cpplint"
-      - name: Run linter
-        run: |
-          bash ./tools/scripts/code_checker.sh
+        run: ./test_shell.sh
